In [1]:
print("hello")

hello

In [5]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from dash import dcc

In [6]:
df = pd.read_csv("project_1_python.csv")

df

,index,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,hosp_patients,...,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,population,median_age,gdp_per_capita,life_expectancy,latitude,longitude
0,0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39835428.0,18.6,1803.987,64.83,33.0,65.0
1,1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39835428.0,18.6,1803.987,64.83,33.0,65.0
2,2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39835428.0,18.6,1803.987,64.83,33.0,65.0
3,3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39835428.0,18.6,1803.987,64.83,33.0,65.0
4,4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39835428.0,18.6,1803.987,64.83,33.0,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180472,190608,ZWE,Africa,Zimbabwe,2022-06-14,254155.0,0.0,5521.0,0.0,NaN,...,6270096.0,4563366.0,1026048.0,NaN,15092171.0,19.6,1899.775,61.49,-20.0,30.0
180473,190609,ZWE,Africa,Zimbabwe,2022-06-15,254387.0,232.0,5525.0,4.0,NaN,...,6271703.0,4567466.0,1027822.0,7481.0,15092171.0,19.6,1899.775,61.49,-20.0,30.0
180474,190610,ZWE,Africa,Zimbabwe,2022-06-16,254502.0,115.0,5526.0,1.0,NaN,...,6274305.0,4570349.0,1029463.0,7126.0,15092171.0,19.6,1899.775,61.49,-20.0,30.0
180475,190611,ZWE,Africa,Zimbabwe,2022-06-17,254753.0,251.0,5533.0,7.0,NaN,...,6276402.0,4574222.0,1031790.0,8297.0,15092171.0,19.6,1899.775,61.49,-20.0,30.0
180476,190612,ZWE,Africa,Zimbabwe,2022-06-18,254753.0,NaN,5533.0,0.0,NaN,...,NaN,NaN,NaN,NaN,15092171.0,19.6,1899.775,61.49,-20.0,30.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180477 entries, 0 to 180476
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   index                    180477 non-null  int64
 1   iso_code                 180477 non-null  str
 2   continent                180477 non-null  str
 3   location                 180477 non-null  str
 4   date                     180477 non-null  str
 5   total_cases              173493 non-null  float64
 6   new_cases                173212 non-null  float64
 7   total_deaths             155323 non-null  float64
 8   new_deaths               155095 non-null  float64
 9   hosp_patients            27152 non-null   float64
 10  total_tests              78326 non-null   float64
 11  new_tests                74509 non-null   float64
 12  tests_per_case           92600 non-null   float64
 13  total_vaccinations       46366 non-null   float64
 14  people_vaccinated        43851 non-null   float64
 15  people_fully_vaccinated  41524 non-null   float64
 16  total_boosters           19866 non-null   float64
 17  new_vaccinations         36940 non-null   float64
 18  population               180477 non-null  float64
 19  median_age               159326 non-null  float64
 20  gdp_per_capita           157994 non-null  float64
 21  life_expectancy          179426 non-null  float64
 22  latitude                 180477 non-null  float64
 23  longitude                180477 non-null  float64
dtypes: float64(19), int64(1), str(4)
memory usage: 33.0 MB

In [16]:
df_countries = df[["iso_code","location","population"]].drop_duplicates()
df_countries = df_countries.sort_values(by="population",ascending=False)

df_countries.head(10)

       iso_code       location    population
33499       CHN          China  1.444216e+09
74570       IND          India  1.393409e+09
170959      USA  United States  3.329151e+08
75441       IDN      Indonesia  2.763618e+08
122998      PAK       Pakistan  2.251999e+08
21805       BRA         Brazil  2.139934e+08
118134      NGA        Nigeria  2.114007e+08
12663       BGD     Bangladesh  1.663035e+08
133450      RUS         Russia  1.459120e+08
103850      MEX         Mexico  1.302622e+08